# Generated by Django 5.0.6 on 2024-08-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tictactoe',
            name='match',
        ),
        migrations.DeleteModel(
            name='RockPaperScissors',
        ),
        migrations.DeleteModel(
            name='TicTacToe',
        ),
    ]
