# Generated by Django 5.0.6 on 2024-08-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_remove_tictactoe_match_delete_rockpaperscissors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToe',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.match')),
                ('board_state', models.CharField(default='         ', max_length=9)),
            ],
        ),
    ]
